### ISSUE TITLE
Picking up boot-node IP fails from time to time

### ISSUE THREAD

**Issue by swiec** [radixdlt/mtps#30]
As title says, from time to time, when running libcloud/mtps.py there is an error:

```
->tools git:(master) ✗ python3 libcloud/mtps.py
Checking if firewall rules are created...
An explorer node seems to be up and running.
/Users/greg/Library/Python/3.7/lib/python/site-packages/paramiko/client.py:828: UserWarning: Unknown ssh-ed25519 host key for 35.246.155.75: b'836a04500f907e2169b783c21eabcfc2'
  key.get_name(), hostname, hexlify(key.get_fingerprint())
Generating new universe...
RADIX_MTPS_NETWORK_START_PUMP:1560931800
Creating boot node...
Updating node finder...
Test will run at: Sun Oct 11 07:23:20 1987
Traceback (most recent call last):
  File "libcloud/mtps.py", line 166, in <module>
    os.environ["RADIX_MTPS_NETWORK_SEEDS"] = boot_node.public_ips[0]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 683, in __setitem__
    value = self.encodevalue(value)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 753, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType
```

**Comment by blenessy** [comment]
#68
